const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  DECREASE_CART_ITEM: 'DECREASE_CART_ITEM'
}

export default CartActionTypes;